name: nosql_persistence
description: Using nosql databases with migrations
version: 0.1.0
repository: https://github.com/meg4cyberc4t/nosql_persistence

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  hive_flutter: ^1.1.0
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
