name: nosql_persistence
description: Using nosql databases with migrations, "expired" data, helpful functions
version: 0.3.1
homepage: https://pub.dev/packages/nosql_persistence
repository: https://github.com/meg4cyberc4t/nosql_persistence

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ">=8.0.0 <10.0.0"
  hive_flutter: ^1.1.0
  meta: ^1.9.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=2.0.0 <4.0.0"
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
